package spankwindows
// spank-windows detects slaps/hits on the laptop and plays audio responses.







































































































































































































































































































































































}	<-done	})))		done <- true	speaker.Play(beep.Seq(streamer, beep.Callback(func() {	done := make(chan bool)	speakerMu.Unlock()	}		*speakerInit = true		speaker.Init(format.SampleRate, format.SampleRate.N(time.Second/10))	if !*speakerInit {	speakerMu.Lock()	defer streamer.Close()	}		}			return			fmt.Fprintf(os.Stderr, "spank: decode %s: %v\n", path, decErr)		if decErr != nil {		streamer, format, decErr = mp3.Decode(io.NopCloser(bytes.NewReader(data)))		var decErr error		}			return			fmt.Fprintf(os.Stderr, "spank: read %s: %v\n", path, err)		if err != nil {		data, err := pack.fs.ReadFile(path)	} else {		}			return			fmt.Fprintf(os.Stderr, "spank: decode %s: %v\n", path, decErr)		if decErr != nil {		streamer, format, decErr = mp3.Decode(file)		var decErr error		defer file.Close()		}			return			fmt.Fprintf(os.Stderr, "spank: open %s: %v\n", path, err)		if err != nil {		file, err := os.Open(path)	if pack.custom {	var format beep.Format	var streamer beep.StreamSeekCloserfunc playAudio(pack *soundPack, path string, speakerInit *bool) {var speakerMu sync.Mutex}	}		}			go playAudio(pack, file, &speakerInit)			fmt.Printf("slap #%d [%s amp=%.5fg] -> %s\n", num, ev.Severity, ev.Amplitude, file)			file := tracker.getFile(score)			num, score := tracker.record(now)			lastYell = now			}				continue			if ev.Amplitude < minAmplitude {			}				continue			if time.Since(lastYell) <= cooldown {			lastEventTime = ev.Time			}				continue			if ev.Time == lastEventTime {			ev := det.Events[len(det.Events)-1]			}				continue			if len(det.Events) == 0 {			det.Process(sample.X, sample.Y, sample.Z, tNow)			tNow := float64(now.UnixNano()) / 1e9			now := time.Now()		case sample := <-samples:			return fmt.Errorf("sensor worker failed: %w", err)		case err := <-sensorErr:			return nil			fmt.Println("\nbye!")		case <-ctx.Done():		select {	for {	samples := reader.Samples()	// Drain samples from the sensor reader channel.	fmt.Printf("spank: listening for slaps in %s mode... (ctrl+c to quit)\n", pack.name)	var lastYell time.Time	var lastEventTime time.Time	det := detector.New()	speakerInit := false	tracker := newSlapTracker(pack, cooldown)func listenForSlaps(ctx context.Context, pack *soundPack, reader *sensor.Reader, cooldown time.Duration) error {}	return listenForSlaps(ctx, pack, reader, cooldown)	cooldown := time.Duration(cooldownMs) * time.Millisecond	time.Sleep(sensorStartupDelay)	// Give the sensor a moment to start producing data.	}()		}			sensorErr <- err		if err := reader.Run(ctx); err != nil {	go func() {	// Start the sensor polling in a background goroutine.	}		return fmt.Errorf("accelerometer init: %w", err)	if err := reader.Init(); err != nil {	defer reader.Close()	reader := sensor.NewReader()	// Initialize the Windows accelerometer sensor.	defer cancel()	ctx, cancel := signal.NotifyContext(ctx, os.Interrupt)	}		return fmt.Errorf("loading %s audio: %w", pack.name, err)	if err := pack.loadFiles(); err != nil {	}		pack = &soundPack{name: "pain", fs: painAudio, dir: "audio/pain", mode: modeRandom}	default:		pack = &soundPack{name: "halo", fs: haloAudio, dir: "audio/halo", mode: modeRandom}	case haloMode:		pack = &soundPack{name: "sexy", fs: sexyAudio, dir: "audio/sexy", mode: modeEscalation}	case sexyMode:		pack = &soundPack{name: "custom", dir: customPath, mode: modeRandom, custom: true}	case customPath != "":	switch {	var pack *soundPack	}		return fmt.Errorf("--min-amplitude must be between 0.0 and 1.0")	if minAmplitude < 0 || minAmplitude > 1 {	}		return fmt.Errorf("--sexy, --halo, and --custom are mutually exclusive; pick one")	if modeCount > 1 {	}		modeCount++	if customPath != "" {	}		modeCount++	if haloMode {	}		modeCount++	if sexyMode {	modeCount := 0func run(ctx context.Context) error {}	}		os.Exit(1)	if err := fang.Execute(context.Background(), cmd); err != nil {	cmd.Flags().IntVar(&cooldownMs, "cooldown", defaultCooldownMs, "Cooldown between responses in milliseconds")	cmd.Flags().Float64Var(&minAmplitude, "min-amplitude", 0.3, "Minimum amplitude threshold (0.0-1.0, lower = more sensitive)")	cmd.Flags().StringVarP(&customPath, "custom", "c", "", "Path to custom MP3 audio directory")	cmd.Flags().BoolVarP(&haloMode, "halo", "H", false, "Enable halo mode")	cmd.Flags().BoolVarP(&sexyMode, "sexy", "s", false, "Enable sexy mode")	}		SilenceUsage: true,		},			return run(cmd.Context())		RunE: func(cmd *cobra.Command, args []string) error {		Version: version,Use --halo to play random audio clips from Halo soundtracks on each slap.`,within a minute, the more intense the sounds become.Use --sexy for a different experience. In sexy mode, the more you slapHP, Dell, and others with motion sensors).Works on Windows laptops with built-in accelerometers (Surface, Lenovo,and plays audio responses when a slap or hit is detected.		Long: `spank reads the Windows accelerometer via the Sensor API		Short: "Yells 'ow!' when you slap the laptop",		Use:   "spank",	cmd := &cobra.Command{func main() {}	return st.pack.files[idx]	}		idx = maxIdx	if idx > maxIdx {	idx := int(float64(len(st.pack.files)) * (1.0 - math.Exp(-(score-1)/st.scale)))	maxIdx := len(st.pack.files) - 1	// Escalation: 1-exp(-x) curve maps score to file index.	}		return st.pack.files[rand.Intn(len(st.pack.files))]	if st.pack.mode == modeRandom {func (st *slapTracker) getFile(score float64) string {}	return st.total, st.score	st.total++	st.lastTime = now	st.score += 1.0	}		st.score *= math.Pow(0.5, elapsed/st.halfLife)		elapsed := now.Sub(st.lastTime).Seconds()	if !st.lastTime.IsZero() {	defer st.mu.Unlock()	st.mu.Lock()func (st *slapTracker) record(now time.Time) (int, float64) {}	}		pack:     pack,		scale:    scale,		halfLife: decayHalfLife,	return &slapTracker{	scale := (ssMax - 1) / math.Log(float64(len(pack.files)+1))	ssMax := 1.0 / (1.0 - math.Pow(0.5, cooldownSec/decayHalfLife))	cooldownSec := cooldown.Seconds()	// maps to the last index.	// state the score converges to ssMax; we set scale so that score	// slapping (one per cooldown) reaches the final file. At steady	// scale maps the exponential curve so that sustained max-ratefunc newSlapTracker(pack *soundPack, cooldown time.Duration) *slapTracker {}	pack     *soundPack	scale    float64 // controls the escalation curve shape	halfLife float64 // seconds	total    int	lastTime time.Time	score    float64	mu       sync.Mutextype slapTracker struct {}	return nil	}		return fmt.Errorf("no audio files found in %s", sp.dir)	if len(sp.files) == 0 {	sort.Strings(sp.files)	}		}			}				sp.files = append(sp.files, sp.dir+"/"+entry.Name())			if !entry.IsDir() {		for _, entry := range entries {		sp.files = make([]string, 0, len(entries))		}			return err		if err != nil {		entries, err := sp.fs.ReadDir(sp.dir)	} else {		}			}				sp.files = append(sp.files, filepath.Join(sp.dir, entry.Name()))			if !entry.IsDir() {		for _, entry := range entries {		sp.files = make([]string, 0, len(entries))		}			return err		if err != nil {		entries, err := os.ReadDir(sp.dir)	if sp.custom {func (sp *soundPack) loadFiles() error {}	custom bool	files  []string	mode   playMode	dir    string	fs     embed.FS	name   stringtype soundPack struct {)	sensorStartupDelay = 100 * time.Millisecond	// sensorStartupDelay gives the sensor time to start producing data.	maxSampleBatch = 200	// per tick to avoid falling behind.	// maxSampleBatch caps the number of accelerometer samples processed	sensorPollInterval = 10 * time.Millisecond	// sensorPollInterval is how often we check for new accelerometer data.	defaultCooldownMs = 750	// defaultCooldownMs is the default cooldown between audio responses.	decayHalfLife = 30.0	// halves. Controls how fast escalation fades.	// decayHalfLife is how many seconds of inactivity before intensityconst ()	modeEscalation	modeRandom playMode = iotaconst (type playMode intvar sensorErr = make(chan error, 1)// sensorErr receives any error from the sensor worker.)	cooldownMs   int	minAmplitude float64	customPath   string	haloMode     bool	sexyMode     boolvar (var haloAudio embed.FS//go:embed audio/halo/*.mp3var sexyAudio embed.FS//go:embed audio/sexy/*.mp3var painAudio embed.FS//go:embed audio/pain/*.mp3var version = "dev")	"github.com/usivagna/Spank-windows/sensor"	"github.com/usivagna/Spank-windows/detector"	"github.com/spf13/cobra"	"github.com/gopxl/beep/v2/speaker"	"github.com/gopxl/beep/v2/mp3"	"github.com/gopxl/beep/v2"	"github.com/charmbracelet/fang"	"time"	"sync"	"sort"	"path/filepath"	"os/signal"	"os"	"math/rand"	"math"	"io"	"fmt"	"embed"	"context"	"bytes"import (package main// daemon required. Windows port of github.com/taigrr/spank.// It reads the accelerometer via the Windows Sensor API — no separate sensor