package sensor
//go:build windows


















































































































































































































































































































































}	r.initialized = false	}		r.sensor = 0		comRelease(r.sensor)	if r.sensor != 0 {	defer r.mu.Unlock()	r.mu.Lock()func (r *Reader) Close() {// Close releases the COM sensor object.}	}		}			}				// Drop sample if channel is full.			default:			case r.samples <- sample:			select {			}				continue				// Skip failed reads; sensor may not have new data yet.			if err != nil {			sample, err := r.readOneSample()		case <-ticker.C:			return nil		case <-ctx.Done():		select {	for {	defer ticker.Stop()	ticker := time.NewTicker(10 * time.Millisecond) // 100 Hz	}		return err	if err := r.Init(); err != nil {func (r *Reader) Run(ctx context.Context) error {// It blocks until the context is cancelled.// Run starts polling the accelerometer and sending samples to the channel.}	}		return 0, fmt.Errorf("unexpected PROPVARIANT type: %d", pv.Vt)	default:		return float64(math.Float32frombits(bits)), nil		bits := *(*uint32)(unsafe.Pointer(&pv.Val))		// VT_R4 is a 32-bit float stored in the first 4 bytes of the union	case vtR4:		return pv.Val, nil	case vtR8:	switch pv.Vt {	}		return 0, err	if err != nil {	)		uintptr(unsafe.Pointer(&pv)),		uintptr(unsafe.Pointer(&key)),	_, err := comCall(report, drVtGetSensorValue,	var pv propVariant	}		Pid:   pid,		Fmtid: sensorDataTypePropertySet,	key := propertyKey{func (r *Reader) readSensorValue(report uintptr, pid uint32) (float64, error) {// readSensorValue reads a float64 value from a data report.}	}, nil		Timestamp: time.Now(),		Z:         z,		Y:         y,		X:         x,	return Sample{	}		return Sample{}, fmt.Errorf("reading Z: %w", err)	if err != nil {	z, err := r.readSensorValue(report, pidAccelZ)	}		return Sample{}, fmt.Errorf("reading Y: %w", err)	if err != nil {	y, err := r.readSensorValue(report, pidAccelY)	}		return Sample{}, fmt.Errorf("reading X: %w", err)	if err != nil {	x, err := r.readSensorValue(report, pidAccelX)	// Read X, Y, Z acceleration values.	defer comRelease(report)	}		return Sample{}, fmt.Errorf("no data report available")	if report == 0 {	}		return Sample{}, fmt.Errorf("GetData failed: %w", err)	if err != nil {	_, err := comCall(r.sensor, sVtGetData, uintptr(unsafe.Pointer(&report)))	var report uintptr	// ISensor::GetData	}		return Sample{}, fmt.Errorf("sensor not initialized")	if r.sensor == 0 {func (r *Reader) readOneSample() (Sample, error) {// readOneSample polls the sensor for one data report and extracts X,Y,Z in g.}	return nil	r.initialized = true	r.sensor = sensorPtr	}		return fmt.Errorf("failed to get accelerometer sensor: %w", err)	if err != nil {	_, err = comCall(sensorCollection, scVtGetAt, 0, uintptr(unsafe.Pointer(&sensorPtr)))	var sensorPtr uintptr	// Get the first sensor.	}		return fmt.Errorf("no accelerometer sensors available (count=%d)", count)	if err != nil || count == 0 {	_, err = comCall(sensorCollection, scVtGetCount, uintptr(unsafe.Pointer(&count)))	var count uint32	// Get count.	defer comRelease(sensorCollection)	}		return fmt.Errorf("no accelerometer found: %w (does this device have an accelerometer?)", err)	if err != nil {	)		uintptr(unsafe.Pointer(&sensorCollection)),		uintptr(unsafe.Pointer(&sensorTypeAccelerometer3D)),	_, err := comCall(sensorManager, smVtGetSensorsByType,	var sensorCollection uintptr	// Get accelerometer sensors.	defer comRelease(sensorManager)	}		return fmt.Errorf("failed to create SensorManager: 0x%08X (is the Windows Sensor service running?)", uint32(ret))	if int32(ret) < 0 {	)		uintptr(unsafe.Pointer(&sensorManager)),		uintptr(unsafe.Pointer(&iidSensorManager)),		1|4, // CLSCTX_INPROC_SERVER | CLSCTX_LOCAL_SERVER		0, // pUnkOuter		uintptr(unsafe.Pointer(&clsidSensorManager)),	ret, _, _ = procCoCreate.Call(	var sensorManager uintptr	// Create ISensorManager instance.	}		return fmt.Errorf("CoInitializeEx failed: 0x%08X", uint32(ret))	if int32(ret) < 0 && int32(ret) != -2147417850 { // RPC_E_CHANGED_MODE is ok	ret, _, _ := procCoInit.Call(0, coinitMTA)	// Initialize COM in MTA mode.	}		return nil	if r.initialized {	defer r.mu.Unlock()	r.mu.Lock()func (r *Reader) Init() error {// Init initializes COM and finds the accelerometer sensor.}	}		comCall(obj, 2) // Release is vtable index 2	if obj != 0 {func comRelease(obj uintptr) {// comRelease calls IUnknown::Release on a COM object.}	return ret, nil	}		return ret, fmt.Errorf("COM call failed: HRESULT 0x%08X (%v)", uint32(ret), err)	if int32(ret) < 0 {	// COM methods return HRESULT; 0 = S_OK	}		ret, _, err = windows.SyscallN(method, allArgs...)	default:		ret, _, err = windows.SyscallN(method, allArgs[0], allArgs[1], allArgs[2], allArgs[3], allArgs[4])	case 5:		ret, _, err = windows.SyscallN(method, allArgs[0], allArgs[1], allArgs[2], allArgs[3])	case 4:		ret, _, err = windows.SyscallN(method, allArgs[0], allArgs[1], allArgs[2])	case 3:		ret, _, err = windows.SyscallN(method, allArgs[0], allArgs[1])	case 2:		ret, _, err = windows.SyscallN(method, allArgs[0])	case 1:	switch len(allArgs) {	var err error	var ret uintptr	allArgs = append(allArgs, args...)	allArgs = append(allArgs, obj) // this pointer	allArgs := make([]uintptr, 0, 1+len(args))	method := *(*uintptr)(unsafe.Pointer(vtable + uintptr(vtableIdx)*unsafe.Sizeof(uintptr(0))))	vtable := *(*uintptr)(unsafe.Pointer(obj))func comCall(obj uintptr, vtableIdx int, args ...uintptr) (uintptr, error) {// comCall invokes a COM method via vtable.}	return r.samplesfunc (r *Reader) Samples() <-chan Sample {// Samples returns the channel on which accelerometer samples are delivered.}	}		samples: make(chan Sample, 1000),	return &Reader{func NewReader() *Reader {// NewReader creates a new Windows accelerometer reader.}	samples     chan Sample	initialized bool	sensor      uintptr // *ISensor COM pointer	mu          sync.Mutextype Reader struct {// Reader reads accelerometer data from the Windows Sensor API.)	drVtGetSensorValue = 4const (// ISensorDataReport vtable indices.)	sVtGetState = 5	sVtGetData = 10const (// ISensor vtable indices.)	scVtGetAt    = 4	scVtGetCount = 3const (// ISensorCollection vtable indices.)	smVtGetSensorsByType = 3 // after QueryInterface, AddRef, Releaseconst (// ISensorManager vtable indices.)	procProgIDFromCLSID = ole32.NewProc("ProgIDFromCLSID")	procCoUninit    = ole32.NewProc("CoUninitialize")	procCoCreate    = ole32.NewProc("CoCreateInstance")	procCoInit      = ole32.NewProc("CoInitializeEx")	ole32           = windows.NewLazySystemDLL("ole32.dll")var ()	coinitMTA = 0x0	vtR4      = 4  // VT_R4	vtR8      = 5  // VT_R8const (}	_padding [8]byte // ensure full 24-byte PROPVARIANT size	Val      float64 // union; for VT_R8 this is the double value	_        [6]byte	Vt       uint16type propVariant struct {// PROPVARIANT simplified — we only need VT_R8 (double).}	Pid   uint32	Fmtid windows.GUIDtype propertyKey struct {// PROPERTYKEY for sensor data fields.)	pidAccelZ = uint32(4)	pidAccelY = uint32(3)	pidAccelX = uint32(2)	}		Data4: [8]byte{0xA9, 0x65, 0xCD, 0x79, 0x7A, 0xAB, 0x56, 0xD5},		Data3: 0x4E48,		Data2: 0x07C5,		Data1: 0x3F8A69A2,	sensorDataTypePropertySet = windows.GUID{	// SENSOR_DATA_TYPE_ACCELERATION_X_G = {3F8A69A2-07C5-4E48-A965-CD797AAB56D5} pid 2	}		Data4: [8]byte{0xBC, 0xD0, 0x35, 0x2A, 0x95, 0x82, 0x81, 0x9D},		Data3: 0x4C78,		Data2: 0xE2D2,		Data1: 0xC2FB0F5F,	sensorTypeAccelerometer3D = windows.GUID{	// SENSOR_TYPE_ACCELEROMETER_3D = {C2FB0F5F-E2D2-4C78-BCD0-352A9582819D}	}		Data4: [8]byte{0x8D, 0x00, 0x6D, 0xCF, 0x15, 0xF8, 0x37, 0x7A},		Data3: 0x42DC,		Data2: 0x45A8,		Data1: 0xBD77DB67,	iidSensorManager = windows.GUID{	// IID_ISensorManager = {BD77DB67-45A8-42DC-8D00-6DCF15F8377A}	}		Data4: [8]byte{0x89, 0x15, 0x9D, 0x61, 0x3C, 0xC5, 0xFA, 0x3E},		Data3: 0x4689,		Data2: 0xFCD2,		Data1: 0x77A1C827,	clsidSensorManager = windows.GUID{	// CLSID_SensorManager = {77A1C827-FCD2-4689-8915-9D613CC5FA3E}var (// GUIDs for the Windows Sensor API COM interfaces.)	"golang.org/x/sys/windows"	"unsafe"	"time"	"sync"	"math"	"fmt"	"context"import (package sensor//   - ISensorDataReport//   - ISensor (SENSOR_TYPE_ACCELEROMETER_3D)//   - ISensorManager (CLSID_SensorManager)// The COM interfaces used://// found in many laptops (Surface, Lenovo, HP, Dell, etc.).// This uses the Windows 7+ Sensor API to access the built-in accelerometer//// Windows Sensor API accelerometer reader using COM ISensorManager.